### ISSUE TITLE
Hide items

### ISSUE THREAD

**Issue by Dominiquini** [raiguard/Factorio-QuickItemSearch#10]
#### Is your feature request related to a problem? Please describe.
When I use the feature provided by this mod, I see items introduced by the mod "Editor Extensions (https://mods.factorio.com/mod/EditorExtensions), even though I'm not playing cheat mode.

#### Describe the solution you'd like
If I don't have cheats enabled, I wouldn't want to see the entities created by the "Editor Extensions" mod indexed!

#### Additional context
---

Thanks.

**Comment by raiguard** [comment]
Unfortunately there's not much I can do about this. In order to fix this, I would need to mark the EE items as hidden, but that comes with its own set of problems. For example, hidden items can't be set as quickbar filters. So they need to remain un-hidden.

At some point, I'm going to do a refresh of this mod to add various features and clean up the code, and when I do that, I'll address this. But for now, we'll both just have to live with it. I'm sorry!

**Comment by raiguard** [comment]
Re-opening this because I'll eventually work on it, just not soon.

**Comment by Dominiquini** [comment]
Thanks.

**Comment by Dominiquini** [comment]
It would not be possible (and interesting) to create a new configuration that is a list of items that should not be indexed by the mod (blacklisted items).

Thanks.

**Comment by raiguard** [comment]
Yes, that is part of the solution I have in mind for this. Unfortunately QIS is very low on my list at the moment, as I am currently trying to find a job. And as for Factorio mods, my main priority is finishing a rewrite of one of my other mods, LTN Manager.

**Comment by raiguard** [comment]
Sourcehut ticket: https://todo.sr.ht/~raiguard/factorio-mods/9

**Comment by raiguard** [comment]
This mod is no longer receiving new features.
